version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/node:12.16.1
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Build
          command: npm run build
      - run:
          name: Test
          command: npm run test --watchAll=false

workflows:
  build-and-test:
    jobs:
      - build-and-test
